name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**.nix"
      - "flake.lock"
  workflow_call:

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - ivan
          - operator
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup SSH for private repository
        uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_REPO_SSH_KEY }}

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run flake check
        run: nix flake check --all-systems

      - name: Build NixOS configuration for ${{ matrix.host }}
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel --print-build-logs
