name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - ivan
          - operator
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH for private repository
        uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_REPO_SSH_KEY }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

      - name: Run flake check
        run: nix flake check --all-systems

      - name: Build NixOS configuration for ${{ matrix.host }}
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel --print-build-logs
